name: runlistcompare
channels:
  - conda-forge
  - bioconda

dependencies:
  - python==3.7
  - treeswift
  - biopython
  - clonalframeml
  - iqtree
  - phyml
  - networkx
  - phyml
  - pytest
  - numpy
