name: runlistcompare2
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - ca-certificates
  - certifi
  - clonalframeml
  - iqtree
  - libcxx
  - libcxxabi
  - libffi
  - libgfortran
  - llvm-openmp
  - mpi
  - msgpack-python
  - ncurses
  - numpy
  - openmp
  - openmpi
  - openssl
  - phyml
  - pip
  - python=2.7.15
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - zlib
  - pip:
    - atomicwrites
    - attrs
    - biopython
    - cogent
    - decorator
    - funcsigs
    - more-itertools
    - networkx
    - pathlib2
    - pluggy
    - py
    - pytest
    - scandir
    - six
    - treeswift